---
- name: Install default
  become: true
  community.general.pacman:
    name: [exo, xdg-user-dirs-gtk]

- name: Install pulseaudio
  become: true
  community.general.pacman:
    name: [pavucontrol]

- name: Install bluetooth
  become: true
  community.general.pacman:
    name:
      - blueberry
      - bluez-utils
      # - blueman

- name: Install fuse
  become: true
  community.general.pacman:
    name: [gvfs, gvfs-nfs, gvfs-smb, gvfs-google, gvfs-gphoto2, gvfs-mtp]

- name: Install applications
  become: true
  community.general.pacman:
    name:
      - baobab
      - catfish
      - gnome-disk-utility
      - geany
      - geany-plugins
      - qalculate-gtk
      - gnome-characters
      - gucharmap
      # - ghex
      - gparted
      - gthumb
      - hardinfo
      - lxappearance
      # - onboard
      - redshift
      - xarchiver
      # - file-roller
      - xautolock
      - freerdp
      - libvncserver
### polkit (better then polkit-gnome
#     - lxsession
