---
- name: Install default
  become: true
  pacman:
    name: [lightdm-gtk-greeter, lightdm-gtk-greeter-settings, exo, xdg-user-dirs-gtk]

- name: Install pulseaudio
  become: true
  pacman:
    name: [pavucontrol]

- name: Install bluetooth
  become: true
  pacman:
    name: [blueberry]
    # - blueman

- name: Install fuse
  become: true
  pacman:
    name: [gvfs, gvfs-nfs, gvfs-smb, gvfs-google, gvfs-gphoto2, gvfs-mtp]

- name: Install applications
  become: true
  pacman:
    name:
      - baobab
      - catfish
      - gnome-disk-utility
      - geany
      - geany-plugins
      - qalculate-gtk
      - gnome-characters
      - gucharmap
      # - ghex
      - gparted
      - gthumb
      - hardinfo
      - lxappearance
      # - onboard
      - redshift
      - xarchiver
      # - file-roller
      - xautolock
      - freerdp
      - libvncserver
### polkit (better then polkit-gnome
#     - lxsession

- name: Populate service facts
  service_facts:

- name: Enable lightdm service
  become: true
  service:
    name: lightdm
    enabled: true

- name: Disable sddm
  become: true
  service:
    name: sddm
    enabled: false
  when: "'sddm' in services"

- name: Allow RSYNC for new super user without SUDO password
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: ^%sudo
    line: "{{ lookup('env','USER') }} ALL=NOPASSWD: /usr/bin/rsync"

- name: Copy lightdm configs
  become: true
  synchronize:
    src: lightdm
    dest: /etc/
    archive: false
    compress: false
    recursive: true

- name: Disallow RSYNC for new super user without SUDO password
  become: true
  lineinfile:
    path: /etc/sudoers
    state: absent
    line: "{{ lookup('env','USER') }} ALL=NOPASSWD: /usr/bin/rsync"
