#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "${SSH_CLIENT:-}" != "" ]] || ! pass show home/home.ams/vault-pass; then
	echo 'Unable to read vault password with "pass" application' >/dev/stderr
	echo 'Please provide vault password manually:' >/dev/stderr
	read -s -r PASSWD
	echo -n "$PASSWD"
fi
