---
- name: Install podman
  become: true
  community.general.pacman:
    name: [buildah, docker-compose, fuse-overlayfs, podman-docker]

- name: Install distrobox
  become: true
  community.general.pacman:
    name: [distrobox]

- name: Add user to subuid
  become: true
  ansible.builtin.lineinfile:
    create: true
    group: root
    owner: root
    mode: '0644'
    path: /etc/subuid
    state: present
    line: "{{ lookup('env', 'USER') }}:100000:65536"

- name: Add user group to subgid
  become: true
  ansible.builtin.lineinfile:
    create: true
    group: root
    owner: root
    mode: '0644'
    path: /etc/subgid
    state: present
    line: "{{ lookup('env', 'USER') }}:100000:65536"

- name: Stat file
  ansible.builtin.stat:
    path: /etc/containers/nodocker
  register: p

- name: Add nodocker file
  become: true
  ansible.builtin.file:
    group: root
    mode: '0644'
    owner: root
    path: /etc/containers/nodocker
    state: touch
  when: p.stat.exists is defined and not p.stat.exists
