---
- name: Install podman
  become: true
  community.general.pacman:
    name:
      - aardvark-dns
      - buildah
      - docker-compose
      - fuse-overlayfs
      - netavark
      - podman
      - podman-compose
      - podman-dnsname
      - podman-docker

- name: Add user to subuid
  become: true
  ansible.builtin.lineinfile:
    create: true
    group: root
    owner: root
    mode: '0644'
    path: /etc/subuid
    state: present
    line: "{{ lookup('env', 'USER') }}:100000:65536"

- name: Add user group to subgid
  become: true
  ansible.builtin.lineinfile:
    create: true
    group: root
    owner: root
    mode: '0644'
    path: /etc/subgid
    state: present
    line: "{{ lookup('env', 'USER') }}:100000:65536"

- name: Add nodocker file
  become: true
  ansible.builtin.file:
    group: root
    mode: '0644'
    owner: root
    path: /etc/containers/nodocker
    state: file
