---
- name: Install podman
  become: true
  pacman:
    name: [buildah, fuse-overlayfs, podman, podman-compose]

- name: Add user to subuid
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subuid
    state: present
    line: "{{ lookup('env','USER') }}:100000:65536"

- name: Add user group to subgid
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subgid
    state: present
    line: "{{ lookup('env','USER') }}:100000:65536"
