---
- name: Copy window manager x0vncserver
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/x0vncserver.service
    mode: '0644'
    owner: root
    group: root
    src: x0vncserver.service

- name: Enable x0vncserver service
  become: true
  ansible.builtin.service:
    name: x0vncserver
    enabled: true
