---
- name: Install yubikey
  become: true
  community.general.pacman:
    name: [yubikey-manager, pam-u2f, libp11, pkcs11-provider]

- name: Install yubikey gui
  when: not terminal_only|default(false)
  become: true
  community.general.pacman:
    name: [yubikey-personalization-gui]
