---
- name: Install samba
  become: true
  community.general.pacman:
    state: present
    name:
      - samba

- name: Enable smb service
  become: true
  ansible.builtin.service:
    enabled: true
    name: smb

- name: Enable nmb services
  become: true
  ansible.builtin.service:
    enabled: true
    name: nmb
