---
- name: Install samba
  become: true
  pacman:
    state: present
    name:
      - samba

- name: Enable smb service
  become: true
  service:
    enabled: true
    name: smb

- name: Enable nmb services
  become: true
  service:
    enabled: true
    name: nmb
