---
- name: Install steam
  become: true
  community.general.pacman:
    name: [steam]

- name: Install mesa support
  become: true
  community.general.pacman:
    name: [mesa, lib32-mesa]

- name: Install AMD support
  become: true
  community.general.pacman:
    name: [vulkan-radeon, lib32-vulkan-radeon]

- name: Install vdpau support
  become: true
  community.general.pacman:
    name: [mesa-vdpau, lib32-mesa-vdpau]

- name: Install vulkan DirectX compatibility
  aur:
    name:
      - dxvk-bin
