---
- name: Enable hdd smart service
  become: true
  ansible.builtin.service:
    name: smartd
    enabled: true

- name: Enable bluetooth services
  become: true
  ansible.builtin.service:
    name: bluetooth
    enabled: true

- name: Enable search service
  become: true
  ansible.builtin.service:
    name: plocate-updatedb.timer
    enabled: true
