---
- name: Install lutris
  become: true
  community.general.pacman:
    name:
      - lutris

- name: Install lutris dependencies
  become: true
  community.general.pacman:
    name:
      - lib32-mesa
      - lib32-vulkan-icd-loader
      - lib32-vulkan-intel
      - vulkan-icd-loader
      - vulkan-intel

- name: Install more lutris dependencies
  become: true
  community.general.pacman:
    name:
      - alsa-lib
      - alsa-plugins
      - giflib
      - gnutls
      - gst-plugins-base-libs
      - gtk3
      - lib32-alsa-lib
      - lib32-alsa-plugins
      - lib32-giflib
      - lib32-gnutls
      - lib32-gst-plugins-base-libs
      - lib32-gtk3
      - lib32-libgcrypt
      - lib32-libgpg-error
      - lib32-libjpeg-turbo
      - lib32-libldap
      - lib32-libpng
      - lib32-libpulse
      - lib32-libva
      - lib32-libxcomposite
      - lib32-libxinerama
      - lib32-libxslt
      - lib32-mpg123
      - lib32-ncurses
      - lib32-openal
      - lib32-opencl-icd-loader
      - lib32-sqlite
      - lib32-v4l-utils
      - libgcrypt
      - libgpg-error
      - libjpeg-turbo
      - libldap
      - libpng
      - libpulse
      - libva
      - libxcomposite
      - libxinerama
      - libxslt
      - mpg123
      - ncurses
      - openal
      - opencl-icd-loader
      - sqlite
      - v4l-utils

- name: Install dxvk
  aur:
    name:
      - dxvk-bin
