---
- name: Install essential tools to make login possible
  become: true
  ansible.builtin.package:
    name: [sudo, git, tmux, vim, zsh]

- name: Set root password
  become: true
  ansible.builtin.user:
    name: root
    password: '{{ root_password }}'

- name: Ensure users group
  ansible.builtin.include_tasks: ensure-users-group.yaml

- name: Copy first login script
  become: true
  ansible.builtin.copy:
    src: first-login
    dest: /usr/local/bin/first-login
    mode: '0755'
    owner: root
    group: root

- name: Copy wireguard test config
  become: true
  ansible.builtin.copy:
    src: home-test1-t.conf
    dest: /var/tmp/home-test1-t.conf
    mode: '0400'
    owner: root
    group: root

- name: Ensure directories exists
  become: true
  ansible.builtin.file:
    path: '{{ item.path }}'
    mode: '{{ item.mode }}'
    owner: root
    group: root
    state: directory
  with_items:
    - {path: /var/lib/AccountsService, mode: '0775'}
    - {path: /var/lib/AccountsService/icons, mode: '0775'}
    - {path: /var/lib/AccountsService/users, mode: '0700'}

- name: Create user
  ansible.builtin.include_tasks: create-user.yaml
  vars:
    user: '{{ item }}'
  with_items: '{{ users }}'

- name: Set authorized_keys
  ansible.builtin.include_tasks: set-authorized_keys.yaml
  vars:
    user: '{{ item }}'
  with_items: '{{ users }}'

- name: Fetch dotfiles
  ansible.builtin.include_tasks: fetch-dotfiles.yaml
  vars:
    user: '{{ item }}'
  with_items: '{{ users }}'
