---
- name: Install video
  become: true
  community.general.pacman:
    name: [mesa]
    # name: [vulkan-intel, xf86-video-intel]

# - name: Install intel gpu
#   become: true
#   community.general.pacman:
#     name: [intel-gpu-tools]

- name: Install vaapi support
  become: true
  community.general.pacman:
    name: [libva-mesa-driver, libva-utils]
    # name: [libva-intel-driver]

# - name: Install vdpau support
#   become: true
#   community.general.pacman:
#     name: [libva-vdpau-driver, libvdpau-va-gl]
