---
- name: Enable grub-btrfsd service
  become: true
  ansible.builtin.service:
    name: grub-btrfsd
    enabled: true
    state: started

- name: Enable snapper timeline timer
  become: true
  ansible.builtin.service:
    name: snapper-timeline.timer
    enabled: true

- name: Enable snapper cleanup timer
  become: true
  ansible.builtin.service:
    name: snapper-cleanup.timer
    enabled: true
