---
- name: Install reflector
  become: true
  community.general.pacman:
    name: [reflector]

- name: Update pacman mirrors
  become: true
  ansible.builtin.command: reflector --country "{{ install_pacman_mirror_country }}" --latest 8 --protocol http --protocol
    https --sort rate --download-timeout 2 --save /etc/pacman.d/mirrorlist
  args:
    creates: /root/.cache/mirrorstatus.json

- name: Install all necessary apps
  become: true
  community.general.pacman:
    name:
      - eza
      - fd
      - git
      - gnu-netcat
      - htop
      - inotify-tools
      - jq
      - lsof
      - moreutils
      - ncdu
      - neovim
      - parallel
      - perl-cpanel-json-xs
      - perl-data-dump
      - perl-datetime-timezone
      - perl-dbd-pg
      - perl-ev
      - perl-image-exiftool
      - perl-io-socket-ssl
      - perl-log-any
      - perl-path-tiny
      - perl-perl-critic
      - perl-rename
      - perl-role-tiny
      - perl-tidy
      - perl-yaml-libyaml
      - perlbrew
      - pigz
      - progress
      - pv
      - pyenv
      - python-neovim
      - ripgrep-all
      - rsync
      - socat
      - strace
      - tmux
      - vifm
      - zsh
