---
- name: Install packages
  become: true
  pacman:
    name: [refind]

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts.processor

- name: Install cpu microcode for Intel
  become: true
  pacman:
    name: [intel-ucode]
  when: ansible_facts.processor | join(' ') | regex_search('intel', ignorecase=True)

- name: Install cpu microcode for AMD
  become: true
  pacman:
    name: [amd-ucode]
  when: ansible_facts.processor | join(' ') | regex_search('amd', ignorecase=True)
