---
- name: Install essential tools
  become: true
  pacman:
    state: present
    name: [sudo, git, neovim, tmux, bash-completion, zsh, zsh-completions, iw, crda, polkit]

- name: Install filesystem/partition tools
  become: true
  pacman:
    state: present
    name: [btrfs-progs, exfat-utils, dosfstools, ntfs-3g, fuseiso, udftools, f2fs-tools, nilfs-utils, sshfs, gpart]
    # - davfs2
    # - mtools

- name: Install man/help
  become: true
  pacman:
    state: present
    name: [man-db, man-pages]

- name: Install search
  become: true
  pacman:
    state: present
    name: [ack, fd, fzf, ripgrep, the_silver_searcher]

- name: Install boot tools
  become: true
  pacman:
    state: present
    name: [intel-ucode, efibootmgr, refind]

- name: Install hdd tools
  become: true
  pacman:
    state: present
    name: [smartmontools, hdparm]
    # - hd-idle

- name: Enable hdd smart service
  become: true
  service:
    name: smartd
    enabled: true

- name: Install common tools
  become: true
  pacman:
    state: present
    name: [acpi, libqalculate, hwinfo, iotop, htop, lsof, strace, lsb-release, neofetch]

- name: Install network tools
  become: true
  pacman:
    state: present
    name: [inetutils, nss-mdns, nfs-utils, cifs-utils, socat, gnu-netcat, rsync]

- name: Install pacman tools
  become: true
  pacman:
    state: present
    name: [pacman-contrib, pcurses, pkgstats, reflector]

- name: Install perl
  become: true
  pacman:
    state: present
    name: [perl, perlbrew]

- name: Install python
  become: true
  pacman:
    state: present
    name: [swig, python, python-pip, python-neovim]
    # - pydf

- name: Install ruby
  become: true
  pacman:
    state: present
    name: [ruby]

- name: Install file management tools
  become: true
  pacman:
    state: present
    name: [vifm, jq, ncdu, cpio, lzop, p7zip, unrar]
    # - progress
    # - pv
    # - inotify-tools

- name: Install barcode/qrcode tools
  become: true
  pacman:
    state: present
    name: [zbar]

# - name: Install backup tools
#   become: true
#   pacman:
#     state: present
#     name:
#       - borg
#       - restic

- name: Install pulseaudio
  become: true
  pacman:
    state: present
    name: [pulseaudio, pulseaudio-alsa, pulseaudio-zeroconf, paprefs, pamixer, pulsemixer]

- name: Install alsa
  become: true
  pacman:
    state: present
    name: [alsa-utils, alsa-plugins]
    # alsa-tools
    # amixer sset Master    unmute
    # amixer sset Speaker   unmute
    # amixer sset Headphone unmute
    # alsamixer
    # speaker-test -c 2

- name: Install bluetooth
  become: true
  pacman:
    state: present
    name: [bluez, bluez-cups, bluez-utils, pulseaudio-bluetooth]

- name: Enable bluetooth services
  become: true
  service:
    name: bluetooth
    enabled: true

- name: Install search
  become: true
  pacman:
    state: present
    name: [mlocate]

- name: Enable search service
  become: true
  service:
    name: updatedb.timer
    enabled: true

- name: Clean unnecessary packages
  become: true
  pacman:
    state: absent
    name: []

- name: Allow RSYNC for new super user without SUDO password
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: ^%sudo
    line: "{{ lookup('env','USER') }} ALL=NOPASSWD: /usr/bin/rsync"

- name: Copy configs
  become: true
  synchronize:
    src: etc
    dest: /
    archive: false
    compress: false
    recursive: true

- name: Disallow RSYNC for new super user without SUDO password
  become: true
  lineinfile:
    path: /etc/sudoers
    state: absent
    line: "{{ lookup('env','USER') }} ALL=NOPASSWD: /usr/bin/rsync"

- name: Enable reflector service
  become: true
  service:
    name: reflector.timer
    enabled: true
