---
- name: Audio encoding
  become: true
  community.general.pacman:
    name: [ffmpeg, ffmpegthumbnailer, mac, opus-tools, vorbis-tools, wavpack]

- name: Video encoding
  become: true
  community.general.pacman:
    name:
      - gstreamer
      - gst-plugins-bad
      - gst-plugins-ugly
# a52dec jasper libdca libdv libmpeg2 libtheora libxv

# - name: CD ripping support
#   become: true
#   community.general.pacman:
#     name:
#       - cdparanoia
#       # - abcde
#       # - cdrdao
#       # - mkcue

# - name: Media decoding/ripping
#   become: true
#   community.general.pacman:
#     name:
#       - libdvdcss
#       - dvd+rw-tools
#       - dvdauthor
#       # - dvgrab
#       - vcdimager
#       - transcode
#       # - sox
#       - emovix

# - name: Media info
#   become: true
#   community.general.pacman:
#     name:
#       - mediainfo

- name: Image encoding
  become: true
  community.general.pacman:
    name: [imagemagick, jhead]

- name: Image viewers (terminal)
  become: true
  community.general.pacman:
    name: [chafa, viu]

- name: Image viewers (gui)
  when: not terminal_only|default(false)
  become: true
  community.general.pacman:
    name:
      - sxiv
#
### image viewers
#   feh
# 	mirage
# 	qiv
# 	gpicview
# 	eog eog-plugins
# 	viewnior
# ## image viewers good but big
# 	nomacs

# - name: Audio players (terminal)
#   become: true
#   community.general.pacman:
#     name: [cmus]

# - name: Audio players (gui)
#   when: not terminal_only|default(false)
#   become: true
#   community.general.pacman:
#     name:
#       - audacious
      # - mpd ncmpcpp mpc
# mkdir -p ~/.cache/mpd
# _enable_user_services mpd

- name: Video players (terminal)
  become: true
  community.general.pacman:
    name: [mpv, mpv-mpris]
