---
- name: Install base fonts
  become: true
  community.general.pacman:
    name: [noto-fonts, noto-fonts-cjk, noto-fonts-emoji, ttf-dejavu, ttf-nerd-fonts-symbols-mono]

- name: Install developer fonts
  become: true
  community.general.pacman:
    name: [ttf-cascadia-code, ttf-fira-code, ttf-jetbrains-mono]

- name: Install additional fonts
  become: true
  community.general.pacman:
    name: [powerline-fonts, ttf-font-awesome, ttf-liberation]

- name: Install emoji support
  become: true
  community.general.pacman:
    name: [ttf-joypixels, unicode-emoji]

# => -------------------------------------------------------------------------------------------------------------- {{{1

- name: Install developer fonts (aur)
  aur:
    name: [ttf-iosevka]

- name: Install additional fonts (aur)
  aur:
    name: [open-dyslexic-fonts, ttf-symbola-free]
