---
- name: Encryption support
  become: true
  communitly.general.pacman:
    name:
      - encfs
      - pass
      - pass-otp
      # - gnome-encfs-manager-bin
      # - gpa
      # - gpg-crypter
      # - keepassxc
      # - libgee
      # - veracrypt

- name: Smartcard support
  become: true
  communitly.general.pacman:
    name:
      - ccid
      - pcsc-tools

- name: Enable smartcard daemon
  become: true
  ansible.builtin.service:
    name: pcscd.socket
    enabled: true
