---
- name: Certificates support
  become: true
  community.general.pacman:
    name: [easyrsa]

- name: Encryption support
  become: true
  community.general.pacman:
    name: [encfs, pass, pass-otp]

- name: Smartcard support
  become: true
  community.general.pacman:
    name: [ccid, pcsc-tools]

- name: Enable smartcard daemon
  become: true
  ansible.builtin.service:
    name: pcscd.socket
    enabled: true
