---
- name: Copy mount files
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/{{ item }}
    mode: '0644'
    owner: root
    group: root
    src: '{{ item }}'
  with_items:
    - media-nfs-home-doc.automount
    - media-nfs-home-doc.mount
    - media-nfs-home-homes.automount
    - media-nfs-home-homes.mount
    - media-nfs-home-music.automount
    - media-nfs-home-music.mount
    - media-nfs-home-video.automount
    - media-nfs-home-video.mount

- name: Enable automounts
  become: true
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: true
  with_items:
    - media-nfs-home-doc.automount
    - media-nfs-home-homes.automount
    - media-nfs-home-music.automount
    - media-nfs-home-video.automount
