---
- name: Install yubikey
  become: true
  community.general.pacman:
    name:
      - yubikey-manager

- name: Install yubikey gui
  when: not terminal_only|default(false)
  become: true
  community.general.pacman:
    name:
      - yubikey-manager-qt
      - yubikey-personalization-gui
