---
- name: Install yubikey
  become: true
  pacman:
    name:
      - yubikey-manager

- name: Install yubikey gui
  when: not terminal_only|default(false)
  become: true
  pacman:
    name:
      - yubikey-personalization-gui
