---
- name: Add the user
  become: true
  user:
    comment: "{{ item.comment }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    append: true
    update_password: on_create
    shell: /bin/zsh
  with_items: "{{ users }}"
  notify:
    - reset root password
    - disable root

- name: Ensure directory exists
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { path: /etc/sudoers.d, mode: "0750" }

- name: Copy additional sudoers
  become: true
  copy:
    src: sudoers.d/additional
    dest: /etc/sudoers.d/additional
    owner: root
    group: root
    mode: "0644"
    force: false

- name: Set proper folder permissions for user
  become: true
  file:
    path: /home/{{ item.user }}
    mode: g=rxs
  with_items: "{{ users }}"

- name: Create ssh directory for user
  become: true
  file:
    path: /home/{{ item.user }}/.ssh
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    state: directory
    mode: "0700"
  with_items: "{{ users }}"
  when: item.create_dot_ssh is not defined or item.create_dot_ssh|bool

- name: Copy authorized_keys for user
  become: true
  copy:
    src: authorized_keys
    dest: /home/{{ item.user }}/.ssh/authorized_keys
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0600"
  with_items: "{{ users }}"
  when: item.create_dot_ssh is not defined or item.create_dot_ssh|bool
