---
- name: Set common variables
  ansible.builtin.include_vars: common.yaml

- name: Set distribution dependent variables
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}.yaml"

- name: Include distribution specific tasks
  ansible.builtin.include_tasks: '{{ ansible_distribution }}.yaml'

# => -------------------------------------------------------------------------------------------------------------- {{{1

- name: Install common required packages
  become: true
  ansible.builtin.package:
    name: '{{ application_packages_common }}'

- name: Install essential tools
  become: true
  ansible.builtin.package:
    name: [bash-completion, git, tmux]

- name: Install essential tools (distribution)
  become: true
  ansible.builtin.package:
    name: '{{ application_packages_essential }}'

- name: Install common tools
  become: true
  ansible.builtin.package:
    name: [eza, htop, lsof, moreutils, strace]

- name: Install network tools
  become: true
  ansible.builtin.package:
    name: [bind, dog, gnu-netcat, rsync, socat, wireguard-tools, xh]

- name: Install network tools (distribution)
  become: true
  ansible.builtin.package:
    name: '{{ application_packages_network }}'

- name: Install network monitoring tools
  become: true
  ansible.builtin.package:
    name: [iftop, iptraf-ng, mtr, nethogs, ngrep, nload, tcpdump, tcpflow, vnstat]

- name: Install man/help
  become: true
  ansible.builtin.package:
    name: [man-pages]

- name: Install man/help (distribution)
  become: true
  ansible.builtin.package:
    name: '{{ application_packages_man }}'

- name: Install search tools
  become: true
  ansible.builtin.package:
    name: [fd, fzf]

- name: Install search tools (distribution)
  become: true
  ansible.builtin.package:
    name: '{{ application_packages_search }}'

- name: Install file management tools
  become: true
  ansible.builtin.package:
    name: [duf, inotify-tools, fuseiso, jq, ncdu, pigz, progress, pv, sshfs, vifm, yq]

- name: Install file management tools (distribution)
  become: true
  ansible.builtin.package:
    name: '{{ application_packages_file }}'

- name: Install highlight tools
  become: true
  ansible.builtin.package:
    name: [bat, git-delta]

- name: Install barcode/qrcode tools
  become: true
  ansible.builtin.package:
    name: [zbar]

- name: Install documentation tools
  become: true
  ansible.builtin.package:
    name: [glow]

# => -------------------------------------------------------------------------------------------------------------- {{{1

- name: Install perl base
  become: true
  ansible.builtin.package:
    name: '{{ application_packages_perl_base }}'

- name: Install perl additional
  become: true
  ansible.builtin.package:
    name: '{{ application_packages_perl_additional }}'

- name: Install python base
  become: true
  ansible.builtin.package:
    name: [swig]

- name: Install python additional
  become: true
  ansible.builtin.package:
    name: '{{ application_packages_python_additional }}'
