---
- name: Install packages
  become: true
  ansible.builtin.package:
    name: [grub, grub-btrfs]

- name: Copy pacman hook
  become: true
  ansible.builtin.copy:
    dest: /usr/share/libalpm/hooks/{{ item }}
    mode: '0644'
    owner: root
    group: root
    src: '{{ item }}'
  with_items: [98-grub-mkconfig.hook, 99-kernel-propagate-efi.hook]

- name: Include distribution specific tasks
  ansible.builtin.include_tasks: '{{ ansible_distribution }}.yaml'

- name: Prepare grub
  become: true
  ansible.builtin.script: prepare-grub.sh

# - name: Ensure directory exists
#   become: true
#   ansible.builtin.file:
#     path: '{{ item.path }}'
#     mode: '{{ item.mode }}'
#     owner: root
#     group: root
#     state: directory
#   with_items:
#     - {path: /etc/sudoers.d, mode: '0750'}

# - name: Copy additional sudoers
#   become: true
#   ansible.builtin.copy:
#     src: sudoers.d/additional
#     dest: /etc/sudoers.d/additional
#     owner: root
#     group: root
#     mode: '0640'
