---
- name: Include distribution specific tasks
  ansible.builtin.include_tasks: '{{ ansible_distribution }}.yaml'

- name: Copy configs files
  become: true
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/snapper/configs
    owner: root
    group: root
    mode: '0644'
  with_fileglob: [etc/snapper/configs/*]
  notify: [Enable snapper timeline timer, Enable snapper cleanup timer]
