---
- name: Include distribution specific tasks
  ansible.builtin.include_tasks: '{{ ansible_distribution }}.yaml'

- name: Copy configs files
  become: true
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/snapper/configs
    owner: root
    group: root
    mode: '0644'
  with_fileglob: [etc/snapper/configs/*]

- name: Enable snapper timeline timer
  become: true
  ansible.builtin.service:
    name: snapper-timeline.timer
    enabled: true

- name: Enable snapper cleanup timer
  become: true
  ansible.builtin.service:
    name: snapper-cleanup.timer
    enabled: true
