---
- name: Install printer brother-mfc-l2710dw
  aur:
    name: [brother-mfc-l2710dw]

- name: Install scanner brother-mfc-l2710dw
  aur:
    name: [brscan4]

- name: Add scanner
  become: true
  shell: brsaneconfig4 -a name=MFC-L2710DW model=MFC-L2710DW ip="mfc.ams"
  args:
    creates: /etc/cups/ppd/Brother_MFC-L2710DW_series.ppd
