---
- name: Install network packages
  become: true
  pacman:
    name:
      - dhclient
      # - network-manager-applet
      - networkmanager
      # - networkmanager-openconnect
      - systemd-resolvconf

- name: Enable NetworkManager service
  become: true
  service:
    name: NetworkManager
    enabled: true
    state: started

- name: Enable systemd-resolved service
  become: true
  service:
    name: systemd-resolved
    enabled: true
    state: started

# - name: Install additional network-manager packages
#   aur:
#     name:
#       - networkmanager-l2tp
#       - networkmanager-libreswan
#       - networkmanager-openvpn
#       - networkmanager-pptp
#       - networkmanager-ssh-git
#       - networkmanager-sstp
#       - networkmanager-strongswan

# /etc/NetworkManager/NetworkManager.conf
# [main]
# dhcp=dhclient
