---
- name: Install network packages
  become: true
  pacman:
    name: [bind]

- name: Install monitoring packages
  become: true
  pacman:
    name: [iptraf-ng, mtr, nethogs, nload, iftop, vnstat, tcpdump, tcpflow]
    # - proxychains
    # - qbittorrent

- name: Install favorite network tools
  become: true
  pacman:
    name: [remmina, freerdp, libvncserver]

# - name: Install openvpn packages
#   become: true
#   pacman:
#     state: present
#     name: [openvpn]

# - name: Install openvpn resolved updater
#   aur:
#     name:
#       - openvpn-update-systemd-resolved

# 	### enable ip forwarding for correct vpns working
# 	sudo sysctl -w net.ipv4.conf.all.forwarding=1
# 	sudo sysctl -w net.ipv6.conf.all.forwarding=1

# - name: Enable vnstat service
#   become: true
#   service:
#     name: vnstat
#     enabled: true
#     state: started
