---
application_packages_essential: [mise, zsh-completions]
application_packages_file: []
application_packages_man: [man-db]
application_packages_network: [base]
application_packages_perl_additional: [perl-rename]
application_packages_perl_base: []
application_packages_python_additional: []
application_packages_search: []
application_packages_vnc: []
