---
- name: Ascii art
  become: true
  community.general.pacman:
    state: present
    name: [aalib, libcaca, mplayer]
    # - aview

- name: Space
  become: true
  community.general.pacman:
    state: present
    name: [kstars, xplanet]

# https://opensource.com/article/18/12/linux-toy-boxes
# telnet towel.blinkenlights.nl
- name: Install fun packages
  aur:
    name:
      - boxes
      - nudoku-git
      - myman
      - asciiquarium
      - nyancat
      - lolcat
      - cowsay
      - ponysay
      - figlet
      - sl
      - espeak
      - cmatrix
