#!/bin/bash

set -e

USR_PAS="$1"
D_HOST="$2"
D_LANG="$3"
D_TIME="$4"

### Update pacman config
sed -i 's|^#Color$|Color\nILoveCandy|'        /mnt/etc/pacman.conf
sed -i 's|^#VerbosePkgLists|VerbosePkgLists|' /mnt/etc/pacman.conf

### set time sync and time zone
# ln -sf "/usr/share/zoneinfo/$D_TIME"          /mnt/etc/localtime
# arch-chroot /mnt hwclock --systohc --utc

### configure language and location
# echo "LANG=$D_LANG"                        >> /mnt/etc/locale.conf

for lang in "$D_LANG" "en_US.UTF-8" "nl_NL.UTF-8" "ru_RU.UTF-8"; do
    sed -i "s|.*\(${lang}\)|\1|"              /mnt/etc/locale.gen
done
arch-chroot /mnt locale-gen >/dev/null

ROOT_PASS=$(perl -MDigest::MD5=md5_hex -E '$pass=shift; $salt=md5_hex(rand); $opt="j9T"; print crypt($pass,"\$y\$${opt}\$${salt}\$")' "$USR_PAS")

args=(
    --hostname="$D_HOST"
    --locale="$D_LANG"
    --root-password-hashed="$ROOT_PASS" # doesn't work for some reason
    --root-shell="/usr/bin/zsh" # doesn't work for some reason
    --timezone="$D_TIME"
    --copy-keymap
)
systemd-firstboot --force --root /mnt "${args[@]}"

arch-chroot /mnt usermod -p "$ROOT_PASS" root
arch-chroot /mnt chsh -s /usr/bin/zsh

### set hostname and network
# echo "$D_HOST"                              > /mnt/etc/hostname

# this is unnecessary as nss-myhostname is enabled in nsswitch.conf
#echo "127.0.1.1 $(cat /mnt/etc/hostname).ams $(cat /mnt/etc/hostname)" >> /mnt/etc/hosts
#echo "127.0.0.1 localhost"                                             >> /mnt/etc/hosts
#echo "::1       localhost"                                             >> /mnt/etc/hosts

### set font for console
#echo FONT=ter-u16n >> /mnt/etc/vconsole.conf
# cp -f /etc/vconsole.conf                      /mnt/etc/vconsole.conf

### set correct environment (let's use personal preferences in ~/.pam_environment)
#echo "EDITOR=vim"     >> /mnt/etc/environment
#echo "VISUAL=vim"     >> /mnt/etc/environment

# sed -i 's|^use-ipv6=yes|use-ipv6=no|'                           /mnt/etc/avahi/avahi-daemon.conf

### configure mdns, enabled llmnr make all resolves to .local very slow
# sed -i 's| resolve | mdns4_minimal [NOTFOUND=return] resolve |' /mnt/etc/nsswitch.conf
ln -sf /run/systemd/resolve/stub-resolv.conf /mnt/etc/resolv.conf

units=(
    NetworkManager
    avahi-daemon
    btrfs-scrub@-.timer
    btrfs-scrub@home.timer
    fstrim.timer
    sshd
    systemd-resolved
    systemd-homed
    systemd-homed-firstboot
)
arch-chroot /mnt systemctl enable "${units[@]}"

cat << EO_DUMMY > /mnt/etc/credstore/home.create.dummy
{
	"disposition" : "regular",
	"environment" : [
		"EDITOR=vim",
		"VISUAL=vim"
	],
	"memberOf" : [
		"wheel"
	],
	"shell" : "/usr/bin/zsh",
	"storage" : "directory",
	"uid" : 60310,
	"userName" : "dummy"
}
EO_DUMMY

mkdir -p                                                      /mnt/etc/skel/git/private/
git clone https://github.com/andrew-grechkin/ansible-arch.git /mnt/etc/skel/git/private/ansible-arch
git clone https://github.com/andrew-grechkin/dotfiles.git     /mnt/etc/skel/git/private/dotfiles

# cat << EO_DUMMY | homectl register - --image-path=/home/dummy.homedir
# {
# 	"disposition" : "regular",
# 	"environment" : [
# 		"EDITOR=vim",
# 		"VISUAL=vim"
# 	],
# 	"privileged" : {
# 		"hashedPassword" : [
# 			"$ROOT_PASS"
# 		]
# 	},
# 	"memberOf" : [
# 		"wheel"
# 	],
# 	"shell" : "/usr/bin/zsh",
# 	"storage" : "directory",
# 	"uid" : 60310,
# 	"userName" : "dummy"
# }
# EO_DUMMY

# mkdir -p /mnt/home/dummy.homedir/git/private
# git clone https://github.com/andrew-grechkin/ansible-arch.git             /mnt/home/dummy.homedir/git/private/ansible-arch
# git clone https://github.com/andrew-grechkin/dotfiles.git                 /mnt/home/dummy.homedir/git/private/dotfiles
# cp -vf /var/lib/systemd/home/dummy.identity                               /mnt/home/dummy.homedir/.identity
# cp -vf /mnt/etc/skel/.zshrc                                               /mnt/home/dummy.homedir/
# jq -S 'del(.binding)' /var/lib/systemd/home/dummy.identity              > /mnt/home/dummy.homedir/.identity
# chown "$(jq -r '"\(.uid):\(.uid)"' /mnt/home/dummy.homedir/.identity)" -R /mnt/home/dummy.homedir
# chmod g-rwx,o-rwx                                                      -R /mnt/home/dummy.homedir

mkdir -p                           /mnt/root/.config/
cp -vaf /root/.config/{git,tmux}   /mnt/root/.config/
cp -vaf /etc/skel/.zshrc           /mnt/root/
rm -rvf --                         /mnt/etc/skel/*bash*

# take keys from the running install image as they are autogenerated there on the fly
# cp -fvar -- /var/lib/systemd/home /mnt/var/lib/systemd/
# cp -fva  -- /etc/machine-id       /mnt/etc/machine-id

cat << EO_ADDITIONAL > /mnt/etc/sudoers.d/additional
Defaults always_set_home
Defaults env_reset
Defaults timestamp_timeout = 30
Defaults env_keep += "DISPLAY SSH_AUTH_SOCK XDG_SESSION_COOKIE"
Defaults env_keep += "LESS PAGER"
Defaults env_keep += "LANGUAGE LANG LC_ADDRESS LC_COLLATE LC_CTYPE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_TIME LC_ALL"
Defaults env_keep += "all_proxy http_proxy https_proxy no_proxy"

Cmnd_Alias  FIREWALL    = /usr/sbin/iptables, /usr/sbin/ip6tables
Cmnd_Alias  KILL        = /usr/bin/killall
Cmnd_Alias  NETWORK     = /usr/bin/netctl, /usr/bin/nmtui, /usr/bin/nmcli, /usr/sbin/ss
Cmnd_Alias  PKGMAN      = /usr/bin/pacman, /usr/bin/apt, /usr/bin/dnf, /usr/bin/yum, /usr/bin/zypper
Cmnd_Alias  POWER       = /usr/sbin/shutdown, /usr/sbin/halt, /usr/sbin/poweroff, /usr/sbin/reboot
Cmnd_Alias  STORAGE     = /usr/sbin/losetup, /usr/bin/umount, /usr/bin/mount -o nosuid\,nodev\,noexec
Cmnd_Alias  SYSTEMD     = /usr/bin/journalctl, /usr/bin/systemctl

%wheel      ALL         = (ALL) ALL
%wheel      ALL         = (ALL) NOPASSWD: PKGMAN, SYSTEMD, KILL, POWER, NETWORK
EO_ADDITIONAL
