---
- name: Install motion
  aur:
    name:
      - motion

- name: Copy motion configs
  become: true
  ansible.builtin.synchronize:
    src: motion
    dest: /etc/
    archive: false
    compress: false
    recursive: true
