- name: Install cups
  become: yes
  pacman:
    state: present
    name:
      - cups
      - cups-pdf
      - cups-pk-helper
      - system-config-printer

- name: Install printer brother-mfc-l2710dw
  become: yes
  become_user: {{ lookup('env','USER') }}
  aur:
    skip_installed: yes
    name:
      - brother-mfc-l2710dw

- name: Enable cups service
  become: yes
  service:
    name: org.cups.cupsd
    enabled: yes
    state: started
