---
- name: Install cups
  become: true
  community.general.pacman:
    name:
      - cups
      - cups-pdf
      - cups-pk-helper
      - system-config-printer

- name: Enable cups service
  become: true
  service:
    name: cups
    enabled: true
    state: started

# - name: Enable cups auto-discovery service
#   become: true
#   service:
#     name: cups-browsed
#     enabled: true
