---
- name: Install cups
  become: true
  pacman:
    name:
      - cups
      - cups-pdf
      - cups-pk-helper
      - system-config-printer

- name: Enable cups service
  become: true
  service:
    name: cups
    enabled: true
    state: started
