---
- name: Audio encoding
  become: true
  pacman:
    name: [ffmpeg, ffmpegthumbnailer, mac, opus-tools, vorbis-tools, wavpack]

- name: Video encoding
  become: true
  pacman:
    name: [gstreamer, gst-plugins-bad, gst-plugins-ugly]
# a52dec jasper libdca libdv libmpeg2 libtheora libxv

- name: CD ripping support
  become: true
  pacman:
    name: [abcde, cdparanoia, cdrdao]
# mkcue

- name: Media decoding/ripping
  become: true
  pacman:
    name: [libdvdcss, dvd+rw-tools, dvdauthor, dvgrab, vcdimager, transcode, sox, emovix]

- name: Media info
  become: true
  pacman:
    name: [mediainfo]

- name: Media info (gui)
  when: not terminal_only|default(false)
  become: true
  pacman:
    name: [mediainfo-gui]

- name: Image encoding
  become: true
  pacman:
    name: [imagemagick]

- name: Image viewers (terminal)
  become: true
  pacman:
    name: [chafa]

- name: Image viewers (gui)
  when: not terminal_only|default(false)
  become: true
  pacman:
    name: [feh, sxiv]
### image viewers
# 	mirage
# 	qiv
# 	gpicview
# 	eog eog-plugins
# 	viewnior
# ## image viewers good but big
# 	nomacs

- name: Audio players (terminal)
  become: true
  pacman:
    name: [cmus]

- name: Audio players (gui)
  when: not terminal_only|default(false)
  become: true
  pacman:
    name: [audacious]
    # - mpd ncmpcpp mpc
# mkdir -p ~/.cache/mpd
# _enable_user_services mpd

- name: Video players (terminal)
  become: true
  pacman:
    name: [mpv]
