---
- name: Arduino
  become: true
  community.general.pacman:
    name:
      - arduino-avr-core
      - arduino-cli
      - arduino-docs
      - arm-none-eabi-gcc
      - arm-none-eabi-newlib
      - stlink
