---
- hosts: [localhost]
  any_errors_fatal: true
  vars:
    install_home_size: 80%FREE
    install_pacman_mirror_country: Netherlands
  vars_prompt:
    - name: install_device
      prompt: Install device
      default: /dev/sda
    - name: install_root_size
      prompt: Root partition size
      default: 48G
    - name: install_swap_size
      prompt: Swap partition size
      default: 16G
    - name: username
      prompt: New user name
    - name: useruid
      prompt: New user uid
      default: 1000
    - name: userpass
      prompt: New user password
      confirm: true
      private: true
    - name: install_encrypt
      prompt: Use LUKS2
      default: false
  roles:
    - installation
