---
- hosts: [localhost]
  any_errors_fatal: true
  vars:
    install_device: /dev/sda
    install_root_size: 48G
    install_swap_size: 16G
    install_home_size: 80%FREE
    install_pacman_mirror_country: Netherlands
  vars_prompt:
    - name: username
      prompt: New user name
      private: false
    - name: useruid
      prompt: New user uid
      private: false
      default: 1000
    - name: userpass
      prompt: New user password
      confirm: true
      private: true
    - name: install_encrypt
      prompt: Use LUKS2
      default: false
  roles:
    - installation
