---
- hosts: [localhost]
  any_errors_fatal: true
  vars:
    install_device: /dev/sda
    install_encrypt: false
    install_root_size: 48G
    install_swap_size: 16G
    install_home_size: 80%FREE
    install_pacman_mirror_country: Netherlands
  roles:
    - installation
