---
- hosts: localhost-not-ready
  any_errors_fatal: true
  vars_prompt:
    - name: install_device
      prompt: Install device
      default: /dev/sda
      private: false
    - name: install_suffix
      prompt: Suffix for all device labels (make labels unique)
      default: ''
      private: false
    - name: install_root_size
      prompt: Root partition size
      default: 64G
      private: false
    - name: install_swap_size
      prompt: Swap partition size
      default: 16G
      private: false
    - name: username
      prompt: New user name
      private: false
    - name: useruid
      prompt: New user uid
      default: '1000'
      private: false
    - name: userpass
      prompt: New user password
      confirm: true
      private: true
    - name: install_encrypt
      prompt: Use LUKS2
      default: 'false'
      private: false
    - name: safe_disk_space_at_the_end
      prompt: Safe 20GiB at the end of the disk
      default: 'true'
      private: false
    - name: default_hostname
      prompt: Default hostname
      default: arch
      private: false
    - name: default_locale
      prompt: Default locale
      default: en_DK.UTF-8
      private: false
    - name: default_timezone
      prompt: Default timezone
      default: Europe/Amsterdam
      private: false
  roles: [system/install]
