---
- hosts: [localhost]
  any_errors_fatal: true
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false
    - name: userpass
      prompt: What is your password?
      confirm: true
      encrypt: sha512_crypt
      private: true
      salt_size: 7
    - name: lukspass
      prompt: Enter luks2 password
      confirm: true
      private: true
  vars:
    install_device: /dev/sda
    install_encrypt: false
    install_root_size: 48G
    install_swap_size: 16G
    install_home_size: 80%FREE
    install_pacman_mirror_country: Netherlands
  roles:
    - installation
