---
- hosts: all
  any_errors_fatal: true
  vars:
    install_pacman_mirror_country: Netherlands
  roles:
    - system/disable-ipv6
    - system/sddm
    - system/sudo
    - application/core/must-have
