- hosts: [arch]
  roles:
    - private/users
    - x/kde
    - application/snapper
    - aur/trizen
    - device/printer
    - device/scanner
    - device/touchpad
    - device/video
    - network/internet
    - network/network
    - application/encryption
    - application/docker
    - application/media
    - application/security
    - application/viewer
    - application/virtualbox
    - aur/archivemount
    - aur/google-chrome
    - aur/pamac
    - aur/skype
