---
- hosts: [localhost]
  roles:
    - x/xfce
    - application/aur/archivemount
    - application/aur/fonts
    - application/aur/google-chrome
    - application/core/browser
    - application/core/encryption
    - application/core/media
    - application/core/network
    - application/core/snapper
    - application/core/viewer
    - device/network
    - device/touchpad
    - device/video
    - device/yubikey
