---
- name: Install devel packages
  become: true
  pacman:
    state: present
    name:
      # - apache
      - gdb
      - perf
      - cmake
      - extra-cmake-modules
      - ninja
      - ctags
      - clang
      - llvm
      - python-pylint
      - bat
      - pygmentize
      - retext
      - tig
      - zeal

- name: Linting
  become: true
  pacman:
    state: present
    name:
      - yamllint
      - vint

- name: Arduino
  become: true
  pacman:
    state: present
    name:
      - arduino-avr-core
      - arduino-cli
      - arduino-docs
      - arm-none-eabi-gcc
      - arm-none-eabi-newlib
      - stlink

- name: Mail
  become: true
  pacman:
    state: present
    name:
      - isync
      - lynx
      - newsboat

# - name: Install VScode
#   pacman:
#     state: present
#     name:
#       - code
#
# - name: Install go packages
#   pacman:
#     state: present
#     name:
#       - go
#       - go-tools
#       - delve
#
# - name: Install emacs
#   pacman:
#     state: present
#     name:
#       - emacs
#       - adobe-source-code-pro-fonts
