---
- name: Reset root password
  become: true
  ansible.builtin.user:
    name: root
    password: '*'

- name: Disable root
  become: true
  ansible.builtin.user:
    name: root
    password_lock: true
