---
- name: Pdf viewers
  become: true
  community.general.pacman:
    name: [zathura, zathura-djvu, zathura-pdf-poppler, poppler]

- name: Pdf support
  become: true
  community.general.pacman:
    name: [pdfgrep, pdftk]

- name: E-book reader
  become: true
  community.general.pacman:
    name: [foliate]

#
# - name: Install fb2 viewers
#   become: true
#   community.general.pacman:
#     name:
#       ## library
#       - freelib
#       - fb2index
#       ## eBook
#       - coolreader
#       - fbreader
#       - fb2edit
