---
- name: Install lightdm
  become: true
  community.general.pacman:
    name:
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Disable sddm
  become: true
  ansible.builtin.service:
    name: sddm
    enabled: false
  when: "'sddm' in services"

- name: Enable lightdm service
  become: true
  ansible.builtin.service:
    name: lightdm
    enabled: true

- name: Copy lightdm configs
  become: true
  synchronize:
    src: lightdm
    dest: /etc/
    archive: false
    compress: false
    recursive: true
