---
- name: Install lightdm
  become: true
  community.general.pacman:
    name: [lightdm-gtk-greeter, lightdm-gtk-greeter-settings]

- name: Populate service facts
  ansible.builtin.service_facts: null

- name: Disable sddm
  become: true
  ansible.builtin.service:
    name: sddm
    enabled: false
  when: "'sddm.service' in ansible_facts.services and ansible_facts.services['sddm.service'].state == 'running'"

- name: Enable lightdm service
  become: true
  ansible.builtin.service:
    enabled: true
    name: lightdm

- name: Stat file
  ansible.builtin.stat:
    path: /etc/lightdm/lightdm-gtk-greeter.conf
  register: p

- name: Copy lightdm configs
  become: true
  synchronize:
    archive: false
    compress: false
    dest: /etc/
    recursive: true
    src: lightdm
  when: p.stat.exists is defined and not p.stat.exists
