---
- name: Install base fonts
  become: true
  pacman:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-dejavu

- name: Install developer fonts
  become: true
  pacman:
    name:
      - ttf-cascadia-code
      - ttf-fira-code
      - ttf-jetbrains-mono

- name: Install developer fonts (aur)
  aur:
    name:
      - nerd-fonts-dejavu-complete
      - nerd-fonts-jetbrains-mono
      - open-dyslexic-fonts
      - ttf-iosevka

- name: Install additional fonts
  become: true
  pacman:
    name:
      # - adobe-source-code-pro-fonts
      # - adobe-source-han-sans-otc-fonts
      # - adobe-source-han-serif-otc-fonts
      # - adobe-source-sans-pro-fonts
      # - inter-font
      # - opendesktop-fonts
      - powerline-fonts
      - ttf-font-awesome
      - ttf-liberation
      # - ttf-linux-libertine
      # - ttf-opensans
