---
- name: Install devel packages
  become: true
  pacman:
    name:
      - gdb
      - git-delta
      - git-sizer
      - perf
      - cmake
      - extra-cmake-modules
      - ninja
      - ctags
      - clang
      - llvm
      - python-pylint
      - bat
      - pygmentize
      # - retext
      # - tig

- name: Linting
  become: true
  pacman:
    name:
      - shellcheck
      - shfmt
      - vint
      - yamllint

# - name: Dictionary
#   become: true
#   pacman:
#     name:
#       - goldendict

- name: Install go support
  become: true
  pacman:
    name:
      - go
      - go-tools
      - delve

- name: Install doc helpers
  aur:
    name:
      - zeal

- name: Install lua support
  aur:
    name:
      - lua-format
      - luarocks

- name: Install perl support
  aur:
    name:
      - perl-mojolicious

- name: Install node.js support
  become: true
  pacman:
    name:
      - nodejs
      - npm
