---
- name: Install ansible
  become: true
  community.general.pacman:
    name: [ansible]

- name: Install asciidoc
  become: true
  community.general.pacman:
    name: [asciidoc, asciidoctor]

- name: Install go support
  become: true
  community.general.pacman:
    name: [go]

- name: Install influxdb support
  community.general.pacman:
    name: [influx-cli]

- name: Install lua support
  aur:
    name: [luarocks]

- name: Install node.js support
  become: true
  community.general.pacman:
    name: [nodejs, npm]

- name: Install perl support
  aur:
    name: [perl-mojolicious]

- name: Install python support
  become: true
  community.general.pacman:
    name: [python-poetry]

- name: Install ruby
  become: true
  community.general.pacman:
    name: [ruby]

- name: Install highlight packages
  become: true
  community.general.pacman:
    name: [bat, git-delta, python-pygmentize]

- name: Install devel packages
  become: true
  community.general.pacman:
    name: [clang, cmake, extra-cmake-modules, gdb, git-sizer, llvm, ninja]

# => -------------------------------------------------------------------------------------------------------------- {{{1

- name: Install tools
  aur:
    name: [task-spooler]
