---
# - name: Install asciidoc
#   become: true
#   community.general.pacman:
#     name: [asciidoc, asciidoctor]

# - name: Install doc helpers
#   become: true
#   community.general.pacman:
#     name:
#       - pandoc
#       - texlive-core

- name: Install devel packages
  become: true
  community.general.pacman:
    name: [gdb, git-sizer, ninja]

- name: Install c/c++ support
  become: true
  community.general.pacman:
    name: [clang, cmake, extra-cmake-modules, llvm]

- name: Install go support
  become: true
  community.general.pacman:
    name: [go]

# - name: Install influxdb support
#   community.general.pacman:
#     name: [influx-cli]

- name: Install lua support
  become: true
  community.general.pacman:
    name: [luarocks]

- name: Install node.js support
  become: true
  community.general.pacman:
    name: [nodejs, npm]

- name: Install python support
  become: true
  community.general.pacman:
    name: [pyenv, python-poetry]

- name: Install ruby
  become: true
  community.general.pacman:
    name: [ruby]
