---
- name: Install devel packages
  become: true
  community.general.pacman:
    name:
      - bat
      - clang
      - cmake
      # - ctags
      - extra-cmake-modules
      - gdb
      - git-delta
      - git-sizer
      - llvm
      - ninja
      - perf
      - pygmentize
      - python-pylint
      # - tig

- name: Linting
  become: true
  community.general.pacman:
    name:
      - shellcheck
      - shfmt
      - vint
      - yamllint

# - name: Dictionary
#   become: true
#   pacman:
#     name:
#       - goldendict

- name: Install go support
  become: true
  community.general.pacman:
    name:
      - go
      - go-tools
      - delve

- name: Install node.js support
  become: true
  community.general.pacman:
    name:
      - nodejs
      - npm

- name: Install elixir support
  become: true
  community.general.pacman:
    name:
      - elixir

- name: Install influxdb support
  community.general.pacman:
    name:
      - influx-cli

- name: Install doc helpers
  kewlfft.aur.aur:
    name:
      - zeal

- name: Install lua support
  kewlfft.aur.aur:
    name:
      - lua-format
      - luarocks

- name: Install perl support
  kewlfft.aur.aur:
    name:
      - perl-mojolicious
