---
- name: Install devel packages
  become: true
  pacman:
    name:
      # - apache
      - gdb
      - perf
      - cmake
      - extra-cmake-modules
      - ninja
      - ctags
      - clang
      - llvm
      - python-pylint
      - bat
      - pygmentize
      # - retext
      - tig
      - zeal

- name: Linting
  become: true
  pacman:
    name:
      - shellcheck
      - vint
      - yamllint

- name: Dictionary
  become: true
  pacman:
    name:
      - goldendict

- name: Install VScode
  become: true
  pacman:
    name:
      - code

- name: Install go support
  become: true
  pacman:
    name:
      - go
      - go-tools
      - delve

- name: Install perl support
  aur:
    name:
      - perl-mojolicious

- name: Install node.js support
  become: true
  pacman:
    name:
      - nodejs

# - name: Install emacs
#   become: true
#   pacman:
#     name:
#       - emacs
#       - adobe-source-code-pro-fonts
